// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MidTest.Net.Data
{
    public partial class QuanLyTranDauDbContext : DbContext
    {
        public QuanLyTranDauDbContext()
        {
        }

        public QuanLyTranDauDbContext(DbContextOptions<QuanLyTranDauDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CauThu> CauThu { get; set; }
        public virtual DbSet<ChiTietTranDau> ChiTietTranDau { get; set; }
        public virtual DbSet<DoiBong> DoiBong { get; set; }
        public virtual DbSet<TranDau> TranDau { get; set; }
        public virtual DbSet<ViTri> ViTri { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=.\\SQLEXPRESS;Initial Catalog=QuanLyTranDau;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CauThu>(entity =>
            {
                entity.HasOne(d => d.DoiBong)
                    .WithMany(p => p.DSCauThu)
                    .HasForeignKey(d => d.IdDoiBong)
                    .HasConstraintName("FK_CauThu_DoiBong");

                entity.HasOne(d => d.ViTri)
                    .WithMany(p => p.CauThu)
                    .HasForeignKey(d => d.IdViTri)
                    .HasConstraintName("FK_CauThu_ViTri");
            });

            modelBuilder.Entity<ChiTietTranDau>(entity =>
            {
                entity.HasKey(e => new { e.IdTranDau, e.IdCauThu });

                entity.HasOne(d => d.CauThu)
                    .WithMany(p => p.ChiTietTranDau)
                    .HasForeignKey(d => d.IdCauThu)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChiTietTranDau_CauThu");

                entity.HasOne(d => d.TranDau)
                    .WithMany(p => p.ChiTietTranDau)
                    .HasForeignKey(d => d.IdTranDau)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ChiTietTranDau_TranDau");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}